// Generated by Bisonc++ V5.02.00 on Mon, 07 Dec 2020 17:49:02 +0100

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {300, 6}, // 1: program (T_PROGRAM) ->  T_PROGRAM T_ID declarations T_BEGIN statements T_END
     {301, 0}, // 2: declarations ->  <empty>
     {301, 2}, // 3: declarations ->  declaration declarations
     {302, 3}, // 4: declaration (T_INTEGER) ->  T_INTEGER T_ID T_SEMICOLON
     {302, 3}, // 5: declaration (T_BOOLEAN) ->  T_BOOLEAN T_ID T_SEMICOLON
     {303, 1}, // 6: statements ->  statement
     {303, 2}, // 7: statements ->  statement statements
     {304, 2}, // 8: statement (T_SKIP) ->  T_SKIP T_SEMICOLON
     {304, 1}, // 9: statement ->  assignment
     {304, 1}, // 10: statement ->  read
     {304, 1}, // 11: statement ->  write
     {304, 1}, // 12: statement ->  branch
     {304, 1}, // 13: statement ->  loop
     {304, 2}, // 14: statement (T_DUPLICATE) ->  T_DUPLICATE statement
     {305, 4}, // 15: assignment (T_ID) ->  T_ID T_ASSIGN expression T_SEMICOLON
     {306, 5}, // 16: read (T_READ) ->  T_READ T_OPEN T_ID T_CLOSE T_SEMICOLON
     {307, 5}, // 17: write (T_WRITE) ->  T_WRITE T_OPEN expression T_CLOSE T_SEMICOLON
     {308, 5}, // 18: branch (T_IF) ->  T_IF expression T_THEN statements T_ENDIF
     {308, 7}, // 19: branch (T_IF) ->  T_IF expression T_THEN statements T_ELSE statements T_ENDIF
     {309, 5}, // 20: loop (T_WHILE) ->  T_WHILE expression T_DO statements T_DONE
     {310, 1}, // 21: expression (T_NUM) ->  T_NUM
     {310, 1}, // 22: expression (T_TRUE) ->  T_TRUE
     {310, 1}, // 23: expression (T_FALSE) ->  T_FALSE
     {310, 1}, // 24: expression (T_ID) ->  T_ID
     {310, 3}, // 25: expression (T_ADD) ->  expression T_ADD expression
     {310, 3}, // 26: expression (T_SUB) ->  expression T_SUB expression
     {310, 3}, // 27: expression (T_MUL) ->  expression T_MUL expression
     {310, 3}, // 28: expression (T_DIV) ->  expression T_DIV expression
     {310, 3}, // 29: expression (T_MOD) ->  expression T_MOD expression
     {310, 3}, // 30: expression (T_LESS) ->  expression T_LESS expression
     {310, 3}, // 31: expression (T_GR) ->  expression T_GR expression
     {310, 3}, // 32: expression (T_EQ) ->  expression T_EQ expression
     {310, 3}, // 33: expression (T_AND) ->  expression T_AND expression
     {310, 3}, // 34: expression (T_OR) ->  expression T_OR expression
     {310, 2}, // 35: expression (T_NOT) ->  T_NOT expression
     {310, 3}, // 36: expression (T_OPEN) ->  T_OPEN expression T_CLOSE
     {311, 1}, // 37: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 3} },             
    { {       300}, { 1} }, // program  
    { {       265}, { 2} }, // T_PROGRAM
    { {         0}, { 0} },             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 2} },        
    { {       287}, { 3} }, // T_ID
    { {         0}, { 0} },        
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  5} },                
    { {     301}, {  4} }, // declarations
    { {     302}, {  5} }, // declaration 
    { {     268}, {  6} }, // T_INTEGER   
    { {     269}, {  7} }, // T_BOOLEAN   
    { {       0}, { -2} },                
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 2} },           
    { {       266}, { 8} }, // T_BEGIN
    { {         0}, { 0} },           
};

SR__ s_5[] =
{
    { { REQ_DEF}, {  5} },                
    { {     301}, {  9} }, // declarations
    { {     302}, {  5} }, // declaration 
    { {     268}, {  6} }, // T_INTEGER   
    { {     269}, {  7} }, // T_BOOLEAN   
    { {       0}, { -2} },                
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       287}, { 10} }, // T_ID
    { {         0}, {  0} },        
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       287}, { 11} }, // T_ID
    { {         0}, {  0} },        
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, { 15} },               
    { {       303}, { 12} }, // statements 
    { {       304}, { 13} }, // statement  
    { {       270}, { 14} }, // T_SKIP     
    { {       305}, { 15} }, // assignment 
    { {       306}, { 16} }, // read       
    { {       307}, { 17} }, // write      
    { {       308}, { 18} }, // branch     
    { {       309}, { 19} }, // loop       
    { {       288}, { 20} }, // T_DUPLICATE
    { {       287}, { 21} }, // T_ID       
    { {       278}, { 22} }, // T_READ     
    { {       279}, { 23} }, // T_WRITE    
    { {       271}, { 24} }, // T_IF       
    { {       275}, { 25} }, // T_WHILE    
    { {         0}, {  0} },               
};

SR__ s_9[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_10[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       280}, { 26} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       280}, { 27} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       267}, { 28} }, // T_END
    { {         0}, {  0} },         
};

SR__ s_13[] =
{
    { { REQ_DEF}, { 15} },               
    { {     303}, { 29} }, // statements 
    { {     304}, { 13} }, // statement  
    { {     270}, { 14} }, // T_SKIP     
    { {     305}, { 15} }, // assignment 
    { {     306}, { 16} }, // read       
    { {     307}, { 17} }, // write      
    { {     308}, { 18} }, // branch     
    { {     309}, { 19} }, // loop       
    { {     288}, { 20} }, // T_DUPLICATE
    { {     287}, { 21} }, // T_ID       
    { {     278}, { 22} }, // T_READ     
    { {     279}, { 23} }, // T_WRITE    
    { {     271}, { 24} }, // T_IF       
    { {     275}, { 25} }, // T_WHILE    
    { {       0}, { -6} },               
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       280}, { 30} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_15[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_16[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_17[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_20[] =
{
    { { REQ_TOKEN}, { 14} },               
    { {       304}, { 31} }, // statement  
    { {       270}, { 14} }, // T_SKIP     
    { {       305}, { 15} }, // assignment 
    { {       306}, { 16} }, // read       
    { {       307}, { 17} }, // write      
    { {       308}, { 18} }, // branch     
    { {       309}, { 19} }, // loop       
    { {       288}, { 20} }, // T_DUPLICATE
    { {       287}, { 21} }, // T_ID       
    { {       278}, { 22} }, // T_READ     
    { {       279}, { 23} }, // T_WRITE    
    { {       271}, { 24} }, // T_IF       
    { {       275}, { 25} }, // T_WHILE    
    { {         0}, {  0} },               
};

SR__ s_21[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       281}, { 32} }, // T_ASSIGN
    { {         0}, {  0} },            
};

SR__ s_22[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       282}, { 33} }, // T_OPEN
    { {         0}, {  0} },          
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       282}, { 34} }, // T_OPEN
    { {         0}, {  0} },          
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 35} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 42} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_26[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_27[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_29[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_30[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -8} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_32[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 43} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_33[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       287}, { 44} }, // T_ID
    { {         0}, {  0} },        
};

SR__ s_34[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 45} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 12} },          
    { {       272}, { 46} }, // T_THEN
    { {       294}, { 47} }, // T_ADD 
    { {       295}, { 48} }, // T_SUB 
    { {       296}, { 49} }, // T_MUL 
    { {       297}, { 50} }, // T_DIV 
    { {       298}, { 51} }, // T_MOD 
    { {       292}, { 52} }, // T_LESS
    { {       293}, { 53} }, // T_GR  
    { {       291}, { 54} }, // T_EQ  
    { {       290}, { 55} }, // T_AND 
    { {       289}, { 56} }, // T_OR  
    { {         0}, {  0} },          
};

SR__ s_36[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_37[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_38[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_39[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_40[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 57} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_41[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 58} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_42[] =
{
    { { REQ_TOKEN}, { 12} },          
    { {       276}, { 59} }, // T_DO  
    { {       294}, { 47} }, // T_ADD 
    { {       295}, { 48} }, // T_SUB 
    { {       296}, { 49} }, // T_MUL 
    { {       297}, { 50} }, // T_DIV 
    { {       298}, { 51} }, // T_MOD 
    { {       292}, { 52} }, // T_LESS
    { {       293}, { 53} }, // T_GR  
    { {       291}, { 54} }, // T_EQ  
    { {       290}, { 55} }, // T_AND 
    { {       289}, { 56} }, // T_OR  
    { {         0}, {  0} },          
};

SR__ s_43[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       280}, { 60} }, // T_SEMICOLON
    { {       294}, { 47} }, // T_ADD      
    { {       295}, { 48} }, // T_SUB      
    { {       296}, { 49} }, // T_MUL      
    { {       297}, { 50} }, // T_DIV      
    { {       298}, { 51} }, // T_MOD      
    { {       292}, { 52} }, // T_LESS     
    { {       293}, { 53} }, // T_GR       
    { {       291}, { 54} }, // T_EQ       
    { {       290}, { 55} }, // T_AND      
    { {       289}, { 56} }, // T_OR       
    { {         0}, {  0} },               
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       283}, { 61} }, // T_CLOSE
    { {         0}, {  0} },           
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       283}, { 62} }, // T_CLOSE
    { {       294}, { 47} }, // T_ADD  
    { {       295}, { 48} }, // T_SUB  
    { {       296}, { 49} }, // T_MUL  
    { {       297}, { 50} }, // T_DIV  
    { {       298}, { 51} }, // T_MOD  
    { {       292}, { 52} }, // T_LESS 
    { {       293}, { 53} }, // T_GR   
    { {       291}, { 54} }, // T_EQ   
    { {       290}, { 55} }, // T_AND  
    { {       289}, { 56} }, // T_OR   
    { {         0}, {  0} },           
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, { 15} },               
    { {       303}, { 63} }, // statements 
    { {       304}, { 13} }, // statement  
    { {       270}, { 14} }, // T_SKIP     
    { {       305}, { 15} }, // assignment 
    { {       306}, { 16} }, // read       
    { {       307}, { 17} }, // write      
    { {       308}, { 18} }, // branch     
    { {       309}, { 19} }, // loop       
    { {       288}, { 20} }, // T_DUPLICATE
    { {       287}, { 21} }, // T_ID       
    { {       278}, { 22} }, // T_READ     
    { {       279}, { 23} }, // T_WRITE    
    { {       271}, { 24} }, // T_IF       
    { {       275}, { 25} }, // T_WHILE    
    { {         0}, {  0} },               
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 64} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 65} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 66} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 67} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 68} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 69} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 70} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 71} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 72} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, {  8} },              
    { {       310}, { 73} }, // expression
    { {       284}, { 36} }, // T_NUM     
    { {       285}, { 37} }, // T_TRUE    
    { {       286}, { 38} }, // T_FALSE   
    { {       287}, { 39} }, // T_ID      
    { {       299}, { 40} }, // T_NOT     
    { {       282}, { 41} }, // T_OPEN    
    { {         0}, {  0} },              
};

SR__ s_57[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -35} }, 
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       283}, { 74} }, // T_CLOSE
    { {       294}, { 47} }, // T_ADD  
    { {       295}, { 48} }, // T_SUB  
    { {       296}, { 49} }, // T_MUL  
    { {       297}, { 50} }, // T_DIV  
    { {       298}, { 51} }, // T_MOD  
    { {       292}, { 52} }, // T_LESS 
    { {       293}, { 53} }, // T_GR   
    { {       291}, { 54} }, // T_EQ   
    { {       290}, { 55} }, // T_AND  
    { {       289}, { 56} }, // T_OR   
    { {         0}, {  0} },           
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, { 15} },               
    { {       303}, { 75} }, // statements 
    { {       304}, { 13} }, // statement  
    { {       270}, { 14} }, // T_SKIP     
    { {       305}, { 15} }, // assignment 
    { {       306}, { 16} }, // read       
    { {       307}, { 17} }, // write      
    { {       308}, { 18} }, // branch     
    { {       309}, { 19} }, // loop       
    { {       288}, { 20} }, // T_DUPLICATE
    { {       287}, { 21} }, // T_ID       
    { {       278}, { 22} }, // T_READ     
    { {       279}, { 23} }, // T_WRITE    
    { {       271}, { 24} }, // T_IF       
    { {       275}, { 25} }, // T_WHILE    
    { {         0}, {  0} },               
};

SR__ s_60[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       280}, { 76} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       280}, { 77} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       274}, { 78} }, // T_ENDIF
    { {       273}, { 79} }, // T_ELSE 
    { {         0}, {  0} },           
};

SR__ s_64[] =
{
    { { REQ_DEF}, {   4} },         
    { {     296}, {  49} }, // T_MUL
    { {     297}, {  50} }, // T_DIV
    { {     298}, {  51} }, // T_MOD
    { {       0}, { -25} },         
};

SR__ s_65[] =
{
    { { REQ_DEF}, {   4} },         
    { {     296}, {  49} }, // T_MUL
    { {     297}, {  50} }, // T_DIV
    { {     298}, {  51} }, // T_MOD
    { {       0}, { -26} },         
};

SR__ s_66[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_67[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_69[] =
{
    { { REQ_DEF}, {   6} },         
    { {     294}, {  47} }, // T_ADD
    { {     295}, {  48} }, // T_SUB
    { {     296}, {  49} }, // T_MUL
    { {     297}, {  50} }, // T_DIV
    { {     298}, {  51} }, // T_MOD
    { {       0}, { -30} },         
};

SR__ s_70[] =
{
    { { REQ_DEF}, {   6} },         
    { {     294}, {  47} }, // T_ADD
    { {     295}, {  48} }, // T_SUB
    { {     296}, {  49} }, // T_MUL
    { {     297}, {  50} }, // T_DIV
    { {     298}, {  51} }, // T_MOD
    { {       0}, { -31} },         
};

SR__ s_71[] =
{
    { { REQ_DEF}, {   8} },          
    { {     294}, {  47} }, // T_ADD 
    { {     295}, {  48} }, // T_SUB 
    { {     296}, {  49} }, // T_MUL 
    { {     297}, {  50} }, // T_DIV 
    { {     298}, {  51} }, // T_MOD 
    { {     292}, {  52} }, // T_LESS
    { {     293}, {  53} }, // T_GR  
    { {       0}, { -32} },          
};

SR__ s_72[] =
{
    { { REQ_DEF}, {   9} },          
    { {     294}, {  47} }, // T_ADD 
    { {     295}, {  48} }, // T_SUB 
    { {     296}, {  49} }, // T_MUL 
    { {     297}, {  50} }, // T_DIV 
    { {     298}, {  51} }, // T_MOD 
    { {     292}, {  52} }, // T_LESS
    { {     293}, {  53} }, // T_GR  
    { {     291}, {  54} }, // T_EQ  
    { {       0}, { -33} },          
};

SR__ s_73[] =
{
    { { REQ_DEF}, {   9} },          
    { {     294}, {  47} }, // T_ADD 
    { {     295}, {  48} }, // T_SUB 
    { {     296}, {  49} }, // T_MUL 
    { {     297}, {  50} }, // T_DIV 
    { {     298}, {  51} }, // T_MOD 
    { {     292}, {  52} }, // T_LESS
    { {     293}, {  53} }, // T_GR  
    { {     291}, {  54} }, // T_EQ  
    { {       0}, { -34} },          
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_75[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       277}, { 80} }, // T_DONE
    { {         0}, {  0} },          
};

SR__ s_76[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -16} }, 
};

SR__ s_77[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_78[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -18} }, 
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, { 15} },               
    { {       303}, { 81} }, // statements 
    { {       304}, { 13} }, // statement  
    { {       270}, { 14} }, // T_SKIP     
    { {       305}, { 15} }, // assignment 
    { {       306}, { 16} }, // read       
    { {       307}, { 17} }, // write      
    { {       308}, { 18} }, // branch     
    { {       309}, { 19} }, // loop       
    { {       288}, { 20} }, // T_DUPLICATE
    { {       287}, { 21} }, // T_ID       
    { {       278}, { 22} }, // T_READ     
    { {       279}, { 23} }, // T_WRITE    
    { {       271}, { 24} }, // T_IF       
    { {       275}, { 25} }, // T_WHILE    
    { {         0}, {  0} },               
};

SR__ s_80[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {  2} },           
    { {       274}, { 82} }, // T_ENDIF
    { {         0}, {  0} },           
};

SR__ s_82[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,
};

} // anonymous namespace ends




// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack__.size();
    if (static_cast<size_t>(d_stackIdx__ + 1) == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
        if (d_valueStack__.capacity() >= newSize)
            d_valueStack__.resize(newSize);
        else
        {
            std::vector<STYPE__> enlarged(newSize);
            for (size_t idx = 0; idx != currentSize; ++idx)
                enlarged[idx] = std::move(d_valueStack__[idx]);
            d_valueStack__.swap(enlarged);
        }
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = std::move(d_val__);
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = std::move(d_nextVal__);
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = std::move(d_val__);
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 54 "while.y"
        {
         std::cout << "global main" << std::endl;
         std::cout << "extern read_unsigned, write_unsigned" << std::endl;
         std::cout << "extern read_boolean, write_boolean" << std::endl;
         std::cout << "segment .bss" << std::endl;
         for(std::pair<std::string,var_data> v : symbol_table)
         {
         if(v.second.decl_type == integer)
         std::cout << v.second.label << ": resd 1" << std::endl;
         if(v.second.decl_type == boolean)
         std::cout << v.second.label << ": resb 1" << std::endl;
         }
         std::cout << std::endl;
         std::cout << "segment .text" << std::endl;
         std::cout << "main:" << std::endl;
         std::cout << *d_vsp__[-1].code << std::endl;
         std::cout << "ret" << std::endl;
         delete d_vsp__[-4].name;
         delete d_vsp__[-1].code;
         }
        break;

        case 2:
#line 78 "while.y"
        {
         }
        break;

        case 3:
#line 82 "while.y"
        {
         }
        break;

        case 4:
#line 88 "while.y"
        {
         if( symbol_table.count(*d_vsp__[-1].name) > 0 )
         {
         std::stringstream ss;
         ss << "Re-declared variable: " << *d_vsp__[-1].name << ".\n"
         << "Line of previous declaration: " << symbol_table[*d_vsp__[-1].name].decl_row << std::endl;
         error( ss.str().c_str() );
         }
         symbol_table[*d_vsp__[-1].name] = var_data( d_loc__.first_line, integer, new_label() );
         delete d_vsp__[-1].name;
         }
        break;

        case 5:
#line 101 "while.y"
        {
         if( symbol_table.count(*d_vsp__[-1].name) > 0 )
         {
         std::stringstream ss;
         ss << "Re-declared variable: " << *d_vsp__[-1].name << ".\n"
         << "Line of previous declaration: " << symbol_table[*d_vsp__[-1].name].decl_row << std::endl;
         error( ss.str().c_str() );
         }
         symbol_table[*d_vsp__[-1].name] = var_data( d_loc__.first_line, boolean, new_label() );
         delete d_vsp__[-1].name;
         }
        break;

        case 6:
#line 116 "while.y"
        {
         d_val__.code = d_vsp__[0].code;
         }
        break;

        case 7:
#line 121 "while.y"
        {
         d_val__.code = new std::string(*d_vsp__[-1].code + *d_vsp__[0].code);
         delete d_vsp__[-1].code;
         delete d_vsp__[0].code;
         }
        break;

        case 8:
#line 130 "while.y"
        {
         d_val__.code = new std::string("nop");
         }
        break;

        case 9:
#line 135 "while.y"
        {
         d_val__.code = d_vsp__[0].code;
         }
        break;

        case 10:
#line 140 "while.y"
        {
         d_val__.code = d_vsp__[0].code;
         }
        break;

        case 11:
#line 145 "while.y"
        {
         d_val__.code = d_vsp__[0].code;
         }
        break;

        case 12:
#line 150 "while.y"
        {
         d_val__.code = d_vsp__[0].code;
         }
        break;

        case 13:
#line 155 "while.y"
        {
         d_val__.code = d_vsp__[0].code;
         }
        break;

        case 14:
#line 160 "while.y"
        {
         std::string start = new_label();
         std::string end = new_label();
         d_val__.code = new std::string(
         "mov eax, 2\n"+
         start + ":\n"+
         "cmp eax, 0\n"+
         "je near " + end + "\n"+
         "push eax\n"+
         *d_vsp__[0].code +
         "pop eax\n" +
         "sub eax, 1\n"+
         "jmp near " + start + "\n"+
         end + ":\n"
         );
         }
        break;

        case 15:
#line 180 "while.y"
        {
         if( symbol_table.count(*d_vsp__[-3].name) == 0 )
         {
         std::stringstream ss;
         ss << "Undeclared variable: " << *d_vsp__[-3].name << std::endl;
         error( ss.str().c_str() );
         }
         if(symbol_table[*d_vsp__[-3].name].decl_type != d_vsp__[-1].expr_desc->expr_type)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         if(d_vsp__[-1].expr_desc->expr_type == integer)
         d_val__.code = new std::string("" +
         d_vsp__[-1].expr_desc->expr_code +
         "mov [" + symbol_table[*d_vsp__[-3].name].label + "], eax\n");
         if(d_vsp__[-1].expr_desc->expr_type == boolean)
         d_val__.code = new std::string("" +
         d_vsp__[-1].expr_desc->expr_code +
         "mov [" + symbol_table[*d_vsp__[-3].name].label + "], al\n");
         delete d_vsp__[-3].name;
         delete d_vsp__[-1].expr_desc;
         }
        break;

        case 16:
#line 208 "while.y"
        {
         if( symbol_table.count(*d_vsp__[-2].name) == 0 )
         {
         std::stringstream ss;
         ss << "Undeclared variable: " << *d_vsp__[-2].name << std::endl;
         error( ss.str().c_str() );
         }
         if(symbol_table[*d_vsp__[-2].name].decl_type == integer)
         {
         d_val__.code = new std::string("call read_unsigned\nmov [" + symbol_table[*d_vsp__[-2].name].label + "], eax\n");
         }
         if(symbol_table[*d_vsp__[-2].name].decl_type == boolean)
         {
         d_val__.code = new std::string("call read_boolean\nmov [" + symbol_table[*d_vsp__[-2].name].label + "], al\n");
         }
         delete d_vsp__[-2].name;
         }
        break;

        case 17:
#line 229 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type == integer)
         {
         d_val__.code = new std::string("" +
         d_vsp__[-2].expr_desc->expr_code +
         "push eax\n" +
         "call write_unsigned\n" +
         "add esp,4\n");
         }
         if(d_vsp__[-2].expr_desc->expr_type == boolean)
         {
         d_val__.code = new std::string(
         "xor eax, eax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "push eax\n" +
         "call write_boolean\n" +
         "add esp,4\n");
         }
         delete d_vsp__[-2].expr_desc;
         }
        break;

        case 18:
#line 253 "while.y"
        {
         if(d_vsp__[-3].expr_desc->expr_type != boolean)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         std::string end = new_label();
         d_val__.code = new std::string("" +
         d_vsp__[-3].expr_desc->expr_code +
         "cmp al, 1\n" +
         "jne near " + end + "\n" +
         *d_vsp__[-1].code +
         end + ":\n");
         delete d_vsp__[-3].expr_desc;
         delete d_vsp__[-1].code;
         }
        break;

        case 19:
#line 272 "while.y"
        {
         if(d_vsp__[-5].expr_desc->expr_type != boolean)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         std::string elsel = new_label();
         std::string end = new_label();
         d_val__.code = new std::string("" +
         d_vsp__[-5].expr_desc->expr_code +
         "cmp al, 1\n" +
         "jne near " + elsel + "\n" +
         *d_vsp__[-3].code +
         "jmp " + end + "\n" +
         elsel + ":\n" +
         *d_vsp__[-1].code +
         end + ":\n");
         delete d_vsp__[-5].expr_desc;
         delete d_vsp__[-3].code;
         delete d_vsp__[-1].code;
         }
        break;

        case 20:
#line 298 "while.y"
        {
         if(d_vsp__[-3].expr_desc->expr_type != boolean)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         std::string start = new_label();
         std::string end = new_label();
         d_val__.code = new std::string("" +
         start + ":\n" +
         d_vsp__[-3].expr_desc->expr_code +
         "cmp al, 1\n" +
         "jne near " + end + "\n" +
         *d_vsp__[-1].code +
         "jmp " + start + "\n" +
         end + ":\n");
         delete d_vsp__[-3].expr_desc;
         delete d_vsp__[-1].code;
         }
        break;

        case 21:
#line 322 "while.y"
        {
         d_val__.expr_desc = new expression_descriptor(integer, "mov eax, " + *d_vsp__[0].name + "\n");
         }
        break;

        case 22:
#line 327 "while.y"
        {
         d_val__.expr_desc = new expression_descriptor(boolean, "mov al, 1\n");
         }
        break;

        case 23:
#line 332 "while.y"
        {
         d_val__.expr_desc = new expression_descriptor(boolean, "mov al, 0\n");
         }
        break;

        case 24:
#line 337 "while.y"
        {
         if( symbol_table.count(*d_vsp__[0].name) == 0 )
         {
         std::stringstream ss;
         ss << "Undeclared variable: " << *d_vsp__[0].name << std::endl;
         error( ss.str().c_str() );
         }
         if(symbol_table[*d_vsp__[0].name].decl_type == integer)
         {
         d_val__.expr_desc = new expression_descriptor(symbol_table[*d_vsp__[0].name].decl_type,
         "mov eax, [" + symbol_table[*d_vsp__[0].name].label + "]\n");
         }
         if(symbol_table[*d_vsp__[0].name].decl_type == boolean)
         {
         d_val__.expr_desc = new expression_descriptor(symbol_table[*d_vsp__[0].name].decl_type,
         "mov al, [" + symbol_table[*d_vsp__[0].name].label + "]\n");
         }
         delete d_vsp__[0].name;
         }
        break;

        case 25:
#line 358 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != integer || d_vsp__[0].expr_desc->expr_type != integer)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(integer, "" +
         d_vsp__[0].expr_desc->expr_code +
         "push eax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop ebx\n" +
         "add eax, ebx\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 26:
#line 376 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != integer || d_vsp__[0].expr_desc->expr_type != integer)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(integer, "" +
         d_vsp__[0].expr_desc->expr_code +
         "push eax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop ebx\n" +
         "sub eax, ebx\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 27:
#line 394 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != integer || d_vsp__[0].expr_desc->expr_type != integer)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(integer, "" +
         d_vsp__[0].expr_desc->expr_code +
         "push eax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop ebx\n" +
         "mul ebx\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 28:
#line 412 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != integer || d_vsp__[0].expr_desc->expr_type != integer)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(integer, std::string("") +
         "xor edx, edx\n" +
         d_vsp__[0].expr_desc->expr_code +
         "push eax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop ebx\n" +
         "div ebx\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 29:
#line 431 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != integer || d_vsp__[0].expr_desc->expr_type != integer)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(integer, std::string("") +
         "xor edx, edx\n" +
         d_vsp__[0].expr_desc->expr_code +
         "push eax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop ebx\n" +
         "div ebx\n" +
         "mov eax, edx\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 30:
#line 451 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != integer || d_vsp__[0].expr_desc->expr_type != integer)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(boolean, "" +
         d_vsp__[0].expr_desc->expr_code +
         "push eax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "setl al\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 31:
#line 470 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != integer || d_vsp__[0].expr_desc->expr_type != integer)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(boolean, "" +
         d_vsp__[0].expr_desc->expr_code +
         "push eax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "setg al\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 32:
#line 489 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != d_vsp__[0].expr_desc->expr_type)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(boolean, "" +
         d_vsp__[0].expr_desc->expr_code +
         "push eax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop ebx\n" +
         "cmp eax, ebx\n" +
         "sete al\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 33:
#line 508 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != boolean || d_vsp__[0].expr_desc->expr_type != boolean)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(boolean, "" +
         d_vsp__[0].expr_desc->expr_code +
         "push ax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop bx\n" +
         "and al, bl\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 34:
#line 526 "while.y"
        {
         if(d_vsp__[-2].expr_desc->expr_type != boolean || d_vsp__[0].expr_desc->expr_type != boolean)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(boolean, "" +
         d_vsp__[0].expr_desc->expr_code +
         "push ax\n" +
         d_vsp__[-2].expr_desc->expr_code +
         "pop bx\n" +
         "or al, bl\n");
         delete d_vsp__[-2].expr_desc;
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 35:
#line 544 "while.y"
        {
         if(d_vsp__[0].expr_desc->expr_type != boolean)
         {
         std::stringstream ss;
         ss << d_loc__.first_line << ": Type error." << std::endl;
         error( ss.str().c_str() );
         }
         d_val__.expr_desc = new expression_descriptor(boolean, "" +
         d_vsp__[0].expr_desc->expr_code +
         "xor al, 1\n");
         delete d_vsp__[0].expr_desc;
         }
        break;

        case 36:
#line 558 "while.y"
        {
         d_val__.expr_desc = new expression_descriptor(d_vsp__[-1].expr_desc->expr_type, "" + d_vsp__[-1].expr_desc->expr_code);
         delete d_vsp__[-1].expr_desc;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



