// Generated by Bisonc++ V5.02.00 on Mon, 19 Oct 2020 17:12:15 +0200

// $insert class.ih
#include "Parser.ih"

// The FIRST element of SR arrays shown below uses `d_type', defining the
// state's type, and `d_lastIdx' containing the last element's index. If
// d_lastIdx contains the REQ_TOKEN bitflag (see below) then the state needs
// a token: if in this state d_token__ is _UNDETERMINED_, nextToken() will be
// called

// The LAST element of SR arrays uses `d_token' containing the last retrieved
// token to speed up the (linear) seach.  Except for the first element of SR
// arrays, the field `d_action' is used to determine what to do next. If
// positive, it represents the next state (used with SHIFT); if zero, it
// indicates `ACCEPT', if negative, -d_action represents the number of the
// rule to reduce to.

// `lookup()' tries to find d_token__ in the current SR array. If it fails, and
// there is no default reduction UNEXPECTED_TOKEN__ is thrown, which is then
// caught by the error-recovery function.

// The error-recovery function will pop elements off the stack until a state
// having bit flag ERR_ITEM is found. This state has a transition on _error_
// which is applied. In this _error_ state, while the current token is not a
// proper continuation, new tokens are obtained by nextToken(). If such a
// token is found, error recovery is successful and the token is
// handled according to the error state's SR table and parsing continues.
// During error recovery semantic actions are ignored.

// A state flagged with the DEF_RED flag will perform a default
// reduction if no other continuations are available for the current token.

// The ACCEPT STATE never shows a default reduction: when it is reached the
// parser returns ACCEPT(). During the grammar
// analysis phase a default reduction may have been defined, but it is
// removed during the state-definition phase.

// So:
//      s_x[] = 
//      {
//                  [_field_1_]         [_field_2_]
//
// First element:   {state-type,        idx of last element},
// Other elements:  {required token,    action to perform},
//                                      ( < 0: reduce, 
//                                          0: ACCEPT,
//                                        > 0: next state)
// Last element:    {set to d_token__,    action to perform}
//      }

// When the --thread-safe option is specified, all static data are defined as
// const. If --thread-safe is not provided, the state-tables are not defined
// as const, since the lookup() function below will modify them


namespace // anonymous
{
    char const author[] = "Frank B. Brokken (f.b.brokken@rug.nl)";

    enum ReservedTokens
    {
        PARSE_ACCEPT     = 0,   // `ACCEPT' TRANSITION
        _UNDETERMINED_   = -2,
        _EOF_            = -1,
        _error_          = 256
    };
    enum StateType       // modify statetype/data.cc when this enum changes
    {
        NORMAL,
        ERR_ITEM,
        REQ_TOKEN,
        ERR_REQ,    // ERR_ITEM | REQ_TOKEN
        DEF_RED,    // state having default reduction
        ERR_DEF,    // ERR_ITEM | DEF_RED
        REQ_DEF,    // REQ_TOKEN | DEF_RED
        ERR_REQ_DEF // ERR_ITEM | REQ_TOKEN | DEF_RED
    };    
    struct PI__     // Production Info
    {
        size_t d_nonTerm; // identification number of this production's
                            // non-terminal 
        size_t d_size;    // number of elements in this production 
    };

    struct SR__     // Shift Reduce info, see its description above
    {
        union
        {
            int _field_1_;      // initializer, allowing initializations 
                                // of the SR s_[] arrays
            int d_type;
            int d_token;
        };
        union
        {
            int _field_2_;

            int d_lastIdx;          // if negative, the state uses SHIFT
            int d_action;           // may be negative (reduce), 
                                    // postive (shift), or 0 (accept)
            size_t d_errorState;    // used with Error states
        };
    };

    // $insert staticdata
    
    enum                        // size to expand the state-stack with when
    {                           // full
        STACK_EXPANSION__ = 10
    };

// Productions Info Records:
PI__ const s_productionInfo[] = 
{
     {0, 0}, // not used: reduction values are negative
     {301, 6}, // 1: program (T_PROGRAM) ->  T_PROGRAM T_ID declarations T_BEGIN statements T_END
     {302, 0}, // 2: declarations ->  <empty>
     {302, 2}, // 3: declarations ->  declaration declarations
     {304, 3}, // 4: declaration (T_INTEGER) ->  T_INTEGER T_ID T_SEMICOLON
     {304, 3}, // 5: declaration (T_BOOLEAN) ->  T_BOOLEAN T_ID T_SEMICOLON
     {304, 3}, // 6: declaration (T_TIME) ->  T_TIME T_ID T_SEMICOLON
     {304, 7}, // 7: declaration (T_INTEGER) ->  T_INTEGER T_ARRAY T_ID T_OPEN_B expression T_CLOSE_B T_SEMICOLON
     {303, 1}, // 8: statements ->  statement
     {303, 2}, // 9: statements ->  statement statements
     {306, 2}, // 10: statement (T_SKIP) ->  T_SKIP T_SEMICOLON
     {306, 1}, // 11: statement ->  assignment
     {306, 1}, // 12: statement ->  read
     {306, 1}, // 13: statement ->  write
     {306, 1}, // 14: statement ->  branch
     {306, 1}, // 15: statement ->  loop
     {312, 1}, // 16: num_sem ->  expression
     {312, 3}, // 17: num_sem (T_COMMA) ->  expression T_COMMA num_sem
     {313, 0}, // 18: num_sem_2 ->  <empty>
     {313, 2}, // 19: num_sem_2 ->  num_sem num_sem_2
     {307, 4}, // 20: assignment (T_ID) ->  T_ID T_ASSIGN expression T_SEMICOLON
     {307, 4}, // 21: assignment (T_ID) ->  T_ID T_ASSIGN T_TIME_STAMP T_SEMICOLON
     {307, 8}, // 22: assignment (T_ID) ->  T_ID T_OPEN_B T_CLOSE_B T_EQ T_OPEN_CURLY_B num_sem_2 T_CLOSE_CURLY_B T_SEMICOLON
     {307, 7}, // 23: assignment (T_ID) ->  T_ID T_OPEN_B expression T_CLOSE_B T_ASSIGN expression T_SEMICOLON
     {308, 5}, // 24: read (T_READ) ->  T_READ T_OPEN T_ID T_CLOSE T_SEMICOLON
     {308, 8}, // 25: read (T_READ) ->  T_READ T_OPEN T_ID T_OPEN_B expression T_CLOSE_B T_CLOSE T_SEMICOLON
     {309, 5}, // 26: write (T_WRITE) ->  T_WRITE T_OPEN expression T_CLOSE T_SEMICOLON
     {310, 5}, // 27: branch (T_IF) ->  T_IF expression T_THEN statements T_ENDIF
     {310, 7}, // 28: branch (T_IF) ->  T_IF expression T_THEN statements T_ELSE statements T_ENDIF
     {311, 5}, // 29: loop (T_WHILE) ->  T_WHILE expression T_DO statements T_DONE
     {305, 1}, // 30: expression (T_NUM) ->  T_NUM
     {305, 1}, // 31: expression (T_TRUE) ->  T_TRUE
     {305, 1}, // 32: expression (T_FALSE) ->  T_FALSE
     {305, 1}, // 33: expression (T_ID) ->  T_ID
     {305, 3}, // 34: expression (T_ADD) ->  expression T_ADD expression
     {305, 3}, // 35: expression (T_SUB) ->  expression T_SUB expression
     {305, 3}, // 36: expression (T_MUL) ->  expression T_MUL expression
     {305, 3}, // 37: expression (T_DIV) ->  expression T_DIV expression
     {305, 3}, // 38: expression (T_MOD) ->  expression T_MOD expression
     {305, 3}, // 39: expression (T_LESS) ->  expression T_LESS expression
     {305, 3}, // 40: expression (T_GR) ->  expression T_GR expression
     {305, 3}, // 41: expression (T_EQ) ->  expression T_EQ expression
     {305, 3}, // 42: expression (T_AND) ->  expression T_AND expression
     {305, 3}, // 43: expression (T_OR) ->  expression T_OR expression
     {305, 2}, // 44: expression (T_NOT) ->  T_NOT expression
     {305, 3}, // 45: expression (T_OPEN) ->  T_OPEN expression T_CLOSE
     {305, 4}, // 46: expression (T_HOUR) ->  T_HOUR T_OPEN T_ID T_CLOSE
     {305, 4}, // 47: expression (T_MINUTE) ->  T_MINUTE T_OPEN T_ID T_CLOSE
     {305, 4}, // 48: expression (T_ID) ->  T_ID T_OPEN_B expression T_CLOSE_B
     {314, 1}, // 49: program_$ ->  program
};

// State info and SR__ transitions for each state.


SR__ s_0[] =
{
    { { REQ_TOKEN}, { 3} },             
    { {       301}, { 1} }, // program  
    { {       257}, { 2} }, // T_PROGRAM
    { {         0}, { 0} },             
};

SR__ s_1[] =
{
    { { REQ_TOKEN}, {            2} }, 
    { {     _EOF_}, { PARSE_ACCEPT} }, 
    { {         0}, {            0} }, 
};

SR__ s_2[] =
{
    { { REQ_TOKEN}, { 2} },        
    { {       283}, { 3} }, // T_ID
    { {         0}, { 0} },        
};

SR__ s_3[] =
{
    { { REQ_DEF}, {  6} },                
    { {     302}, {  4} }, // declarations
    { {     304}, {  5} }, // declaration 
    { {     260}, {  6} }, // T_INTEGER   
    { {     261}, {  7} }, // T_BOOLEAN   
    { {     262}, {  8} }, // T_TIME      
    { {       0}, { -2} },                
};

SR__ s_4[] =
{
    { { REQ_TOKEN}, { 2} },           
    { {       258}, { 9} }, // T_BEGIN
    { {         0}, { 0} },           
};

SR__ s_5[] =
{
    { { REQ_DEF}, {  6} },                
    { {     302}, { 10} }, // declarations
    { {     304}, {  5} }, // declaration 
    { {     260}, {  6} }, // T_INTEGER   
    { {     261}, {  7} }, // T_BOOLEAN   
    { {     262}, {  8} }, // T_TIME      
    { {       0}, { -2} },                
};

SR__ s_6[] =
{
    { { REQ_TOKEN}, {  3} },           
    { {       283}, { 11} }, // T_ID   
    { {       284}, { 12} }, // T_ARRAY
    { {         0}, {  0} },           
};

SR__ s_7[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       283}, { 13} }, // T_ID
    { {         0}, {  0} },        
};

SR__ s_8[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       283}, { 14} }, // T_ID
    { {         0}, {  0} },        
};

SR__ s_9[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       303}, { 15} }, // statements
    { {       306}, { 16} }, // statement 
    { {       263}, { 17} }, // T_SKIP    
    { {       307}, { 18} }, // assignment
    { {       308}, { 19} }, // read      
    { {       309}, { 20} }, // write     
    { {       310}, { 21} }, // branch    
    { {       311}, { 22} }, // loop      
    { {       283}, { 23} }, // T_ID      
    { {       271}, { 24} }, // T_READ    
    { {       272}, { 25} }, // T_WRITE   
    { {       264}, { 26} }, // T_IF      
    { {       268}, { 27} }, // T_WHILE   
    { {         0}, {  0} },              
};

SR__ s_10[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -3} }, 
};

SR__ s_11[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       275}, { 28} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_12[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       283}, { 29} }, // T_ID
    { {         0}, {  0} },        
};

SR__ s_13[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       275}, { 30} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_14[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       275}, { 31} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_15[] =
{
    { { REQ_TOKEN}, {  2} },         
    { {       259}, { 32} }, // T_END
    { {         0}, {  0} },         
};

SR__ s_16[] =
{
    { { REQ_DEF}, { 14} },              
    { {     303}, { 33} }, // statements
    { {     306}, { 16} }, // statement 
    { {     263}, { 17} }, // T_SKIP    
    { {     307}, { 18} }, // assignment
    { {     308}, { 19} }, // read      
    { {     309}, { 20} }, // write     
    { {     310}, { 21} }, // branch    
    { {     311}, { 22} }, // loop      
    { {     283}, { 23} }, // T_ID      
    { {     271}, { 24} }, // T_READ    
    { {     272}, { 25} }, // T_WRITE   
    { {     264}, { 26} }, // T_IF      
    { {     268}, { 27} }, // T_WHILE   
    { {       0}, { -8} },              
};

SR__ s_17[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       275}, { 34} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_18[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -11} }, 
};

SR__ s_19[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -12} }, 
};

SR__ s_20[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -13} }, 
};

SR__ s_21[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -14} }, 
};

SR__ s_22[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -15} }, 
};

SR__ s_23[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       276}, { 35} }, // T_ASSIGN
    { {       287}, { 36} }, // T_OPEN_B
    { {         0}, {  0} },            
};

SR__ s_24[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       277}, { 37} }, // T_OPEN
    { {         0}, {  0} },          
};

SR__ s_25[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       277}, { 38} }, // T_OPEN
    { {         0}, {  0} },          
};

SR__ s_26[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 39} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_27[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 48} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_28[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -4} }, 
};

SR__ s_29[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       287}, { 49} }, // T_OPEN_B
    { {         0}, {  0} },            
};

SR__ s_30[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -5} }, 
};

SR__ s_31[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -6} }, 
};

SR__ s_32[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -1} }, 
};

SR__ s_33[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -9} }, 
};

SR__ s_34[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -10} }, 
};

SR__ s_35[] =
{
    { { REQ_TOKEN}, { 11} },                
    { {       305}, { 50} }, // expression  
    { {       282}, { 51} }, // T_TIME_STAMP
    { {       279}, { 40} }, // T_NUM       
    { {       280}, { 41} }, // T_TRUE      
    { {       281}, { 42} }, // T_FALSE     
    { {       283}, { 43} }, // T_ID        
    { {       300}, { 44} }, // T_NOT       
    { {       277}, { 45} }, // T_OPEN      
    { {       273}, { 46} }, // T_HOUR      
    { {       274}, { 47} }, // T_MINUTE    
    { {         0}, {  0} },                
};

SR__ s_36[] =
{
    { { REQ_TOKEN}, { 11} },              
    { {       288}, { 52} }, // T_CLOSE_B 
    { {       305}, { 53} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_37[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       283}, { 54} }, // T_ID
    { {         0}, {  0} },        
};

SR__ s_38[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 55} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_39[] =
{
    { { REQ_TOKEN}, { 12} },          
    { {       265}, { 56} }, // T_THEN
    { {       295}, { 57} }, // T_ADD 
    { {       296}, { 58} }, // T_SUB 
    { {       297}, { 59} }, // T_MUL 
    { {       298}, { 60} }, // T_DIV 
    { {       299}, { 61} }, // T_MOD 
    { {       293}, { 62} }, // T_LESS
    { {       294}, { 63} }, // T_GR  
    { {       292}, { 64} }, // T_EQ  
    { {       291}, { 65} }, // T_AND 
    { {       290}, { 66} }, // T_OR  
    { {         0}, {  0} },          
};

SR__ s_40[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -30} }, 
};

SR__ s_41[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -31} }, 
};

SR__ s_42[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -32} }, 
};

SR__ s_43[] =
{
    { { REQ_DEF}, {   2} },            
    { {     287}, {  67} }, // T_OPEN_B
    { {       0}, { -33} },            
};

SR__ s_44[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 68} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_45[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 69} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_46[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       277}, { 70} }, // T_OPEN
    { {         0}, {  0} },          
};

SR__ s_47[] =
{
    { { REQ_TOKEN}, {  2} },          
    { {       277}, { 71} }, // T_OPEN
    { {         0}, {  0} },          
};

SR__ s_48[] =
{
    { { REQ_TOKEN}, { 12} },          
    { {       269}, { 72} }, // T_DO  
    { {       295}, { 57} }, // T_ADD 
    { {       296}, { 58} }, // T_SUB 
    { {       297}, { 59} }, // T_MUL 
    { {       298}, { 60} }, // T_DIV 
    { {       299}, { 61} }, // T_MOD 
    { {       293}, { 62} }, // T_LESS
    { {       294}, { 63} }, // T_GR  
    { {       292}, { 64} }, // T_EQ  
    { {       291}, { 65} }, // T_AND 
    { {       290}, { 66} }, // T_OR  
    { {         0}, {  0} },          
};

SR__ s_49[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 73} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_50[] =
{
    { { REQ_TOKEN}, { 12} },               
    { {       275}, { 74} }, // T_SEMICOLON
    { {       295}, { 57} }, // T_ADD      
    { {       296}, { 58} }, // T_SUB      
    { {       297}, { 59} }, // T_MUL      
    { {       298}, { 60} }, // T_DIV      
    { {       299}, { 61} }, // T_MOD      
    { {       293}, { 62} }, // T_LESS     
    { {       294}, { 63} }, // T_GR       
    { {       292}, { 64} }, // T_EQ       
    { {       291}, { 65} }, // T_AND      
    { {       290}, { 66} }, // T_OR       
    { {         0}, {  0} },               
};

SR__ s_51[] =
{
    { { REQ_TOKEN}, {  2} },               
    { {       275}, { 75} }, // T_SEMICOLON
    { {         0}, {  0} },               
};

SR__ s_52[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       292}, { 76} }, // T_EQ
    { {         0}, {  0} },        
};

SR__ s_53[] =
{
    { { REQ_TOKEN}, { 12} },             
    { {       288}, { 77} }, // T_CLOSE_B
    { {       295}, { 57} }, // T_ADD    
    { {       296}, { 58} }, // T_SUB    
    { {       297}, { 59} }, // T_MUL    
    { {       298}, { 60} }, // T_DIV    
    { {       299}, { 61} }, // T_MOD    
    { {       293}, { 62} }, // T_LESS   
    { {       294}, { 63} }, // T_GR     
    { {       292}, { 64} }, // T_EQ     
    { {       291}, { 65} }, // T_AND    
    { {       290}, { 66} }, // T_OR     
    { {         0}, {  0} },             
};

SR__ s_54[] =
{
    { { REQ_TOKEN}, {  3} },            
    { {       278}, { 78} }, // T_CLOSE 
    { {       287}, { 79} }, // T_OPEN_B
    { {         0}, {  0} },            
};

SR__ s_55[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       278}, { 80} }, // T_CLOSE
    { {       295}, { 57} }, // T_ADD  
    { {       296}, { 58} }, // T_SUB  
    { {       297}, { 59} }, // T_MUL  
    { {       298}, { 60} }, // T_DIV  
    { {       299}, { 61} }, // T_MOD  
    { {       293}, { 62} }, // T_LESS 
    { {       294}, { 63} }, // T_GR   
    { {       292}, { 64} }, // T_EQ   
    { {       291}, { 65} }, // T_AND  
    { {       290}, { 66} }, // T_OR   
    { {         0}, {  0} },           
};

SR__ s_56[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       303}, { 81} }, // statements
    { {       306}, { 16} }, // statement 
    { {       263}, { 17} }, // T_SKIP    
    { {       307}, { 18} }, // assignment
    { {       308}, { 19} }, // read      
    { {       309}, { 20} }, // write     
    { {       310}, { 21} }, // branch    
    { {       311}, { 22} }, // loop      
    { {       283}, { 23} }, // T_ID      
    { {       271}, { 24} }, // T_READ    
    { {       272}, { 25} }, // T_WRITE   
    { {       264}, { 26} }, // T_IF      
    { {       268}, { 27} }, // T_WHILE   
    { {         0}, {  0} },              
};

SR__ s_57[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 82} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_58[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 83} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_59[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 84} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_60[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 85} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_61[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 86} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_62[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 87} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_63[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 88} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_64[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 89} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_65[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 90} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_66[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 91} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_67[] =
{
    { { REQ_TOKEN}, { 10} },              
    { {       305}, { 92} }, // expression
    { {       279}, { 40} }, // T_NUM     
    { {       280}, { 41} }, // T_TRUE    
    { {       281}, { 42} }, // T_FALSE   
    { {       283}, { 43} }, // T_ID      
    { {       300}, { 44} }, // T_NOT     
    { {       277}, { 45} }, // T_OPEN    
    { {       273}, { 46} }, // T_HOUR    
    { {       274}, { 47} }, // T_MINUTE  
    { {         0}, {  0} },              
};

SR__ s_68[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -44} }, 
};

SR__ s_69[] =
{
    { { REQ_TOKEN}, { 12} },           
    { {       278}, { 93} }, // T_CLOSE
    { {       295}, { 57} }, // T_ADD  
    { {       296}, { 58} }, // T_SUB  
    { {       297}, { 59} }, // T_MUL  
    { {       298}, { 60} }, // T_DIV  
    { {       299}, { 61} }, // T_MOD  
    { {       293}, { 62} }, // T_LESS 
    { {       294}, { 63} }, // T_GR   
    { {       292}, { 64} }, // T_EQ   
    { {       291}, { 65} }, // T_AND  
    { {       290}, { 66} }, // T_OR   
    { {         0}, {  0} },           
};

SR__ s_70[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       283}, { 94} }, // T_ID
    { {         0}, {  0} },        
};

SR__ s_71[] =
{
    { { REQ_TOKEN}, {  2} },        
    { {       283}, { 95} }, // T_ID
    { {         0}, {  0} },        
};

SR__ s_72[] =
{
    { { REQ_TOKEN}, { 14} },              
    { {       303}, { 96} }, // statements
    { {       306}, { 16} }, // statement 
    { {       263}, { 17} }, // T_SKIP    
    { {       307}, { 18} }, // assignment
    { {       308}, { 19} }, // read      
    { {       309}, { 20} }, // write     
    { {       310}, { 21} }, // branch    
    { {       311}, { 22} }, // loop      
    { {       283}, { 23} }, // T_ID      
    { {       271}, { 24} }, // T_READ    
    { {       272}, { 25} }, // T_WRITE   
    { {       264}, { 26} }, // T_IF      
    { {       268}, { 27} }, // T_WHILE   
    { {         0}, {  0} },              
};

SR__ s_73[] =
{
    { { REQ_TOKEN}, { 12} },             
    { {       288}, { 97} }, // T_CLOSE_B
    { {       295}, { 57} }, // T_ADD    
    { {       296}, { 58} }, // T_SUB    
    { {       297}, { 59} }, // T_MUL    
    { {       298}, { 60} }, // T_DIV    
    { {       299}, { 61} }, // T_MOD    
    { {       293}, { 62} }, // T_LESS   
    { {       294}, { 63} }, // T_GR     
    { {       292}, { 64} }, // T_EQ     
    { {       291}, { 65} }, // T_AND    
    { {       290}, { 66} }, // T_OR     
    { {         0}, {  0} },             
};

SR__ s_74[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -20} }, 
};

SR__ s_75[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -21} }, 
};

SR__ s_76[] =
{
    { { REQ_TOKEN}, {  2} },                  
    { {       285}, { 98} }, // T_OPEN_CURLY_B
    { {         0}, {  0} },                  
};

SR__ s_77[] =
{
    { { REQ_TOKEN}, {  2} },            
    { {       276}, { 99} }, // T_ASSIGN
    { {         0}, {  0} },            
};

SR__ s_78[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       275}, { 100} }, // T_SEMICOLON
    { {         0}, {   0} },               
};

SR__ s_79[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       305}, { 101} }, // expression
    { {       279}, {  40} }, // T_NUM     
    { {       280}, {  41} }, // T_TRUE    
    { {       281}, {  42} }, // T_FALSE   
    { {       283}, {  43} }, // T_ID      
    { {       300}, {  44} }, // T_NOT     
    { {       277}, {  45} }, // T_OPEN    
    { {       273}, {  46} }, // T_HOUR    
    { {       274}, {  47} }, // T_MINUTE  
    { {         0}, {   0} },              
};

SR__ s_80[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       275}, { 102} }, // T_SEMICOLON
    { {         0}, {   0} },               
};

SR__ s_81[] =
{
    { { REQ_TOKEN}, {   3} },           
    { {       267}, { 103} }, // T_ENDIF
    { {       266}, { 104} }, // T_ELSE 
    { {         0}, {   0} },           
};

SR__ s_82[] =
{
    { { REQ_DEF}, {   4} },         
    { {     297}, {  59} }, // T_MUL
    { {     298}, {  60} }, // T_DIV
    { {     299}, {  61} }, // T_MOD
    { {       0}, { -34} },         
};

SR__ s_83[] =
{
    { { REQ_DEF}, {   4} },         
    { {     297}, {  59} }, // T_MUL
    { {     298}, {  60} }, // T_DIV
    { {     299}, {  61} }, // T_MOD
    { {       0}, { -35} },         
};

SR__ s_84[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -36} }, 
};

SR__ s_85[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -37} }, 
};

SR__ s_86[] =
{
    { { REQ_DEF}, {   1} }, 
    { {       0}, { -38} }, 
};

SR__ s_87[] =
{
    { { REQ_DEF}, {   6} },         
    { {     295}, {  57} }, // T_ADD
    { {     296}, {  58} }, // T_SUB
    { {     297}, {  59} }, // T_MUL
    { {     298}, {  60} }, // T_DIV
    { {     299}, {  61} }, // T_MOD
    { {       0}, { -39} },         
};

SR__ s_88[] =
{
    { { REQ_DEF}, {   6} },         
    { {     295}, {  57} }, // T_ADD
    { {     296}, {  58} }, // T_SUB
    { {     297}, {  59} }, // T_MUL
    { {     298}, {  60} }, // T_DIV
    { {     299}, {  61} }, // T_MOD
    { {       0}, { -40} },         
};

SR__ s_89[] =
{
    { { REQ_DEF}, {   8} },          
    { {     295}, {  57} }, // T_ADD 
    { {     296}, {  58} }, // T_SUB 
    { {     297}, {  59} }, // T_MUL 
    { {     298}, {  60} }, // T_DIV 
    { {     299}, {  61} }, // T_MOD 
    { {     293}, {  62} }, // T_LESS
    { {     294}, {  63} }, // T_GR  
    { {       0}, { -41} },          
};

SR__ s_90[] =
{
    { { REQ_DEF}, {   9} },          
    { {     295}, {  57} }, // T_ADD 
    { {     296}, {  58} }, // T_SUB 
    { {     297}, {  59} }, // T_MUL 
    { {     298}, {  60} }, // T_DIV 
    { {     299}, {  61} }, // T_MOD 
    { {     293}, {  62} }, // T_LESS
    { {     294}, {  63} }, // T_GR  
    { {     292}, {  64} }, // T_EQ  
    { {       0}, { -42} },          
};

SR__ s_91[] =
{
    { { REQ_DEF}, {   9} },          
    { {     295}, {  57} }, // T_ADD 
    { {     296}, {  58} }, // T_SUB 
    { {     297}, {  59} }, // T_MUL 
    { {     298}, {  60} }, // T_DIV 
    { {     299}, {  61} }, // T_MOD 
    { {     293}, {  62} }, // T_LESS
    { {     294}, {  63} }, // T_GR  
    { {     292}, {  64} }, // T_EQ  
    { {       0}, { -43} },          
};

SR__ s_92[] =
{
    { { REQ_TOKEN}, {  12} },             
    { {       288}, { 105} }, // T_CLOSE_B
    { {       295}, {  57} }, // T_ADD    
    { {       296}, {  58} }, // T_SUB    
    { {       297}, {  59} }, // T_MUL    
    { {       298}, {  60} }, // T_DIV    
    { {       299}, {  61} }, // T_MOD    
    { {       293}, {  62} }, // T_LESS   
    { {       294}, {  63} }, // T_GR     
    { {       292}, {  64} }, // T_EQ     
    { {       291}, {  65} }, // T_AND    
    { {       290}, {  66} }, // T_OR     
    { {         0}, {   0} },             
};

SR__ s_93[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -45} }, 
};

SR__ s_94[] =
{
    { { REQ_TOKEN}, {   2} },           
    { {       278}, { 106} }, // T_CLOSE
    { {         0}, {   0} },           
};

SR__ s_95[] =
{
    { { REQ_TOKEN}, {   2} },           
    { {       278}, { 107} }, // T_CLOSE
    { {         0}, {   0} },           
};

SR__ s_96[] =
{
    { { REQ_TOKEN}, {   2} },          
    { {       270}, { 108} }, // T_DONE
    { {         0}, {   0} },          
};

SR__ s_97[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       275}, { 109} }, // T_SEMICOLON
    { {         0}, {   0} },               
};

SR__ s_98[] =
{
    { { REQ_DEF}, {  12} },              
    { {     313}, { 110} }, // num_sem_2 
    { {     312}, { 111} }, // num_sem   
    { {     305}, { 112} }, // expression
    { {     279}, {  40} }, // T_NUM     
    { {     280}, {  41} }, // T_TRUE    
    { {     281}, {  42} }, // T_FALSE   
    { {     283}, {  43} }, // T_ID      
    { {     300}, {  44} }, // T_NOT     
    { {     277}, {  45} }, // T_OPEN    
    { {     273}, {  46} }, // T_HOUR    
    { {     274}, {  47} }, // T_MINUTE  
    { {       0}, { -18} },              
};

SR__ s_99[] =
{
    { { REQ_TOKEN}, {  10} },              
    { {       305}, { 113} }, // expression
    { {       279}, {  40} }, // T_NUM     
    { {       280}, {  41} }, // T_TRUE    
    { {       281}, {  42} }, // T_FALSE   
    { {       283}, {  43} }, // T_ID      
    { {       300}, {  44} }, // T_NOT     
    { {       277}, {  45} }, // T_OPEN    
    { {       273}, {  46} }, // T_HOUR    
    { {       274}, {  47} }, // T_MINUTE  
    { {         0}, {   0} },              
};

SR__ s_100[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -24} }, 
};

SR__ s_101[] =
{
    { { REQ_TOKEN}, {  12} },             
    { {       288}, { 114} }, // T_CLOSE_B
    { {       295}, {  57} }, // T_ADD    
    { {       296}, {  58} }, // T_SUB    
    { {       297}, {  59} }, // T_MUL    
    { {       298}, {  60} }, // T_DIV    
    { {       299}, {  61} }, // T_MOD    
    { {       293}, {  62} }, // T_LESS   
    { {       294}, {  63} }, // T_GR     
    { {       292}, {  64} }, // T_EQ     
    { {       291}, {  65} }, // T_AND    
    { {       290}, {  66} }, // T_OR     
    { {         0}, {   0} },             
};

SR__ s_102[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -26} }, 
};

SR__ s_103[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -27} }, 
};

SR__ s_104[] =
{
    { { REQ_TOKEN}, {  14} },              
    { {       303}, { 115} }, // statements
    { {       306}, {  16} }, // statement 
    { {       263}, {  17} }, // T_SKIP    
    { {       307}, {  18} }, // assignment
    { {       308}, {  19} }, // read      
    { {       309}, {  20} }, // write     
    { {       310}, {  21} }, // branch    
    { {       311}, {  22} }, // loop      
    { {       283}, {  23} }, // T_ID      
    { {       271}, {  24} }, // T_READ    
    { {       272}, {  25} }, // T_WRITE   
    { {       264}, {  26} }, // T_IF      
    { {       268}, {  27} }, // T_WHILE   
    { {         0}, {   0} },              
};

SR__ s_105[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -48} }, 
};

SR__ s_106[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -46} }, 
};

SR__ s_107[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -47} }, 
};

SR__ s_108[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -29} }, 
};

SR__ s_109[] =
{
    { { DEF_RED}, {  1} }, 
    { {       0}, { -7} }, 
};

SR__ s_110[] =
{
    { { REQ_TOKEN}, {   2} },                   
    { {       286}, { 116} }, // T_CLOSE_CURLY_B
    { {         0}, {   0} },                   
};

SR__ s_111[] =
{
    { { REQ_DEF}, {  12} },              
    { {     313}, { 117} }, // num_sem_2 
    { {     312}, { 111} }, // num_sem   
    { {     305}, { 112} }, // expression
    { {     279}, {  40} }, // T_NUM     
    { {     280}, {  41} }, // T_TRUE    
    { {     281}, {  42} }, // T_FALSE   
    { {     283}, {  43} }, // T_ID      
    { {     300}, {  44} }, // T_NOT     
    { {     277}, {  45} }, // T_OPEN    
    { {     273}, {  46} }, // T_HOUR    
    { {     274}, {  47} }, // T_MINUTE  
    { {       0}, { -18} },              
};

SR__ s_112[] =
{
    { { REQ_DEF}, {  12} },           
    { {     289}, { 118} }, // T_COMMA
    { {     295}, {  57} }, // T_ADD  
    { {     296}, {  58} }, // T_SUB  
    { {     297}, {  59} }, // T_MUL  
    { {     298}, {  60} }, // T_DIV  
    { {     299}, {  61} }, // T_MOD  
    { {     293}, {  62} }, // T_LESS 
    { {     294}, {  63} }, // T_GR   
    { {     292}, {  64} }, // T_EQ   
    { {     291}, {  65} }, // T_AND  
    { {     290}, {  66} }, // T_OR   
    { {       0}, { -16} },           
};

SR__ s_113[] =
{
    { { REQ_TOKEN}, {  12} },               
    { {       275}, { 119} }, // T_SEMICOLON
    { {       295}, {  57} }, // T_ADD      
    { {       296}, {  58} }, // T_SUB      
    { {       297}, {  59} }, // T_MUL      
    { {       298}, {  60} }, // T_DIV      
    { {       299}, {  61} }, // T_MOD      
    { {       293}, {  62} }, // T_LESS     
    { {       294}, {  63} }, // T_GR       
    { {       292}, {  64} }, // T_EQ       
    { {       291}, {  65} }, // T_AND      
    { {       290}, {  66} }, // T_OR       
    { {         0}, {   0} },               
};

SR__ s_114[] =
{
    { { REQ_TOKEN}, {   2} },           
    { {       278}, { 120} }, // T_CLOSE
    { {         0}, {   0} },           
};

SR__ s_115[] =
{
    { { REQ_TOKEN}, {   2} },           
    { {       267}, { 121} }, // T_ENDIF
    { {         0}, {   0} },           
};

SR__ s_116[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       275}, { 122} }, // T_SEMICOLON
    { {         0}, {   0} },               
};

SR__ s_117[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -19} }, 
};

SR__ s_118[] =
{
    { { REQ_TOKEN}, {  11} },              
    { {       312}, { 123} }, // num_sem   
    { {       305}, { 112} }, // expression
    { {       279}, {  40} }, // T_NUM     
    { {       280}, {  41} }, // T_TRUE    
    { {       281}, {  42} }, // T_FALSE   
    { {       283}, {  43} }, // T_ID      
    { {       300}, {  44} }, // T_NOT     
    { {       277}, {  45} }, // T_OPEN    
    { {       273}, {  46} }, // T_HOUR    
    { {       274}, {  47} }, // T_MINUTE  
    { {         0}, {   0} },              
};

SR__ s_119[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -23} }, 
};

SR__ s_120[] =
{
    { { REQ_TOKEN}, {   2} },               
    { {       275}, { 124} }, // T_SEMICOLON
    { {         0}, {   0} },               
};

SR__ s_121[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -28} }, 
};

SR__ s_122[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -22} }, 
};

SR__ s_123[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -17} }, 
};

SR__ s_124[] =
{
    { { DEF_RED}, {   1} }, 
    { {       0}, { -25} }, 
};


// State array:
SR__ *s_state[] =
{
  s_0,  s_1,  s_2,  s_3,  s_4,  s_5,  s_6,  s_7,  s_8,  s_9,
  s_10,  s_11,  s_12,  s_13,  s_14,  s_15,  s_16,  s_17,  s_18,  s_19,
  s_20,  s_21,  s_22,  s_23,  s_24,  s_25,  s_26,  s_27,  s_28,  s_29,
  s_30,  s_31,  s_32,  s_33,  s_34,  s_35,  s_36,  s_37,  s_38,  s_39,
  s_40,  s_41,  s_42,  s_43,  s_44,  s_45,  s_46,  s_47,  s_48,  s_49,
  s_50,  s_51,  s_52,  s_53,  s_54,  s_55,  s_56,  s_57,  s_58,  s_59,
  s_60,  s_61,  s_62,  s_63,  s_64,  s_65,  s_66,  s_67,  s_68,  s_69,
  s_70,  s_71,  s_72,  s_73,  s_74,  s_75,  s_76,  s_77,  s_78,  s_79,
  s_80,  s_81,  s_82,  s_83,  s_84,  s_85,  s_86,  s_87,  s_88,  s_89,
  s_90,  s_91,  s_92,  s_93,  s_94,  s_95,  s_96,  s_97,  s_98,  s_99,
  s_100,  s_101,  s_102,  s_103,  s_104,  s_105,  s_106,  s_107,  s_108,  s_109,
  s_110,  s_111,  s_112,  s_113,  s_114,  s_115,  s_116,  s_117,  s_118,  s_119,
  s_120,  s_121,  s_122,  s_123,  s_124,
};

} // anonymous namespace ends




// If the parsing function call uses arguments, then provide an overloaded
// function.  The code below doesn't rely on parameters, so no arguments are
// required.  Furthermore, parse uses a function try block to allow us to do
// ACCEPT and ABORT from anywhere, even from within members called by actions,
// simply throwing the appropriate exceptions.

ParserBase::ParserBase()
:
    // $insert requiredtokens
    d_requiredTokens__(0),
    d_acceptedTokens__(d_requiredTokens__),
    d_token__(_UNDETERMINED_),
    d_nextToken__(_UNDETERMINED_)
{}


void ParserBase::setDebug(bool mode)
{
    d_actionCases__ = false;
    d_debug__ = mode;
}

void ParserBase::setDebug(DebugMode__ mode)
{
    d_actionCases__ = mode & ACTIONCASES;
    d_debug__ =       mode & ON;
}

void Parser::print__()
{
// $insert print
}

void ParserBase::clearin()
{
    d_token__ = d_nextToken__ = _UNDETERMINED_;
}

void ParserBase::push__(size_t state)
{
    size_t currentSize = d_stateStack__.size();
    if (static_cast<size_t>(d_stackIdx__ + 1) == currentSize)
    {
        size_t newSize = currentSize + STACK_EXPANSION__;
        d_stateStack__.resize(newSize);
        // $insert LTYPEresize
        d_locationStack__.resize(newSize);
        if (d_valueStack__.capacity() >= newSize)
            d_valueStack__.resize(newSize);
        else
        {
            std::vector<STYPE__> enlarged(newSize);
            for (size_t idx = 0; idx != currentSize; ++idx)
                enlarged[idx] = std::move(d_valueStack__[idx]);
            d_valueStack__.swap(enlarged);
        }
    }
    ++d_stackIdx__;
    d_stateStack__[d_stackIdx__] = d_state__ = state;
    // $insert LTYPEpush
    *(d_lsp__ = &d_locationStack__[d_stackIdx__]) = d_loc__;
    *(d_vsp__ = &d_valueStack__[d_stackIdx__]) = std::move(d_val__);
}

void ParserBase::popToken__()
{
    d_token__ = d_nextToken__;

    d_val__ = std::move(d_nextVal__);
    d_nextVal__ = STYPE__();

    d_nextToken__ = _UNDETERMINED_;
}
     
void ParserBase::pushToken__(int token)
{
    d_nextToken__ = d_token__;
    d_nextVal__ = std::move(d_val__);
    d_token__ = token;
}
     
void ParserBase::pop__(size_t count)
{
    if (d_stackIdx__ < static_cast<int>(count))
    {
        ABORT();
    }

    d_stackIdx__ -= count;
    d_state__ = d_stateStack__[d_stackIdx__];
    d_vsp__ = &d_valueStack__[d_stackIdx__];
    // $insert LTYPEpop
    d_lsp__ = &d_locationStack__[d_stackIdx__];
}

inline size_t ParserBase::top__() const
{
    return d_stateStack__[d_stackIdx__];
}

void Parser::executeAction(int production)
try
{
    if (d_token__ != _UNDETERMINED_)
        pushToken__(d_token__);     // save an already available token

    switch (production)
    {
        // $insert actioncases
        
        case 1:
#line 53 "while.y"
        {
         std::cout << "start -> T_PROGRAM T_ID declarations T_BEGIN statements T_END" << std::endl;
         }
        break;

        case 2:
#line 60 "while.y"
        {
         std::cout << "declarations -> epsilon" << std::endl;
         }
        break;

        case 3:
#line 65 "while.y"
        {
         std::cout << "declarations -> declaration declarations" << std::endl;
         }
        break;

        case 4:
#line 72 "while.y"
        {
         std::cout << "declaration -> T_INTEGER T_ID T_SEMICOLON" << std::endl;
         }
        break;

        case 5:
#line 77 "while.y"
        {
         std::cout << "declaration -> T_BOOLEAN T_ID T_SEMICOLON" << std::endl;
         }
        break;

        case 6:
#line 82 "while.y"
        {
         std::cout << "declaration -> T_TIME_STAMP T_ID T_SEMICOLON" << std::endl;
         }
        break;

        case 7:
#line 87 "while.y"
        {
         std::cout << "declaration -> T_INTEGER T_ARRAY T_ID T_OPEN_B expression T_CLOSE_B T_SEMICOLON" << std::endl;
         }
        break;

        case 8:
#line 94 "while.y"
        {
         std::cout << "statements -> statement" << std::endl;
         }
        break;

        case 9:
#line 99 "while.y"
        {
         std::cout << "statements -> statement statements" << std::endl;
         }
        break;

        case 10:
#line 106 "while.y"
        {
         std::cout << "statement -> T_SKIP T_SEMICOLON" << std::endl;
         }
        break;

        case 11:
#line 111 "while.y"
        {
         std::cout << "statement -> assignment" << std::endl;
         }
        break;

        case 12:
#line 116 "while.y"
        {
         std::cout << "statement -> read" << std::endl;
         }
        break;

        case 13:
#line 121 "while.y"
        {
         std::cout << "statement -> write" << std::endl;
         }
        break;

        case 14:
#line 126 "while.y"
        {
         std::cout << "statement -> branch" << std::endl;
         }
        break;

        case 15:
#line 131 "while.y"
        {
         std::cout << "statement -> loop" << std::endl;
         }
        break;

        case 16:
#line 138 "while.y"
        {
         std::cout << "num_sem ->  expression" << std::endl;
         }
        break;

        case 17:
#line 143 "while.y"
        {
         std::cout << "num_sem ->  expression T_COMMA num_sem" << std::endl;
         }
        break;

        case 19:
#line 152 "while.y"
        {
            d_val__ = d_vsp__[-1];
        }
        break;

        case 20:
#line 156 "while.y"
        {
         std::cout << "assignment -> T_ID T_ASSIGN expression T_SEMICOLON" << std::endl;
         }
        break;

        case 21:
#line 161 "while.y"
        {
         std::cout << "assignment -> T_ID T_ASSIGN T_TIME_STAMP T_SEMICOLON" << std::endl;
         }
        break;

        case 22:
#line 166 "while.y"
        {
         std::cout << "assignment -> T_ID T_ASSIGN T_TIME_STAMP T_SEMICOLON" << std::endl;
         }
        break;

        case 23:
#line 171 "while.y"
        {
         std::cout << "assignment -> T_ID T_OPEN_B expression T_CLOSE_B T_ASSIGN expression T_SEMICOLON" << std::endl;
         }
        break;

        case 24:
#line 178 "while.y"
        {
         std::cout << "read -> T_READ T_OPEN T_ID T_CLOSE T_SEMICOLON" << std::endl;
         }
        break;

        case 25:
#line 183 "while.y"
        {
         std::cout << "read -> T_READ T_OPEN T_ID T_CLOSE T_SEMICOLON" << std::endl; 
         }
        break;

        case 26:
#line 190 "while.y"
        {
         std::cout << "write -> T_WRITE T_OPEN expression T_CLOSE T_SEMICOLON" << std::endl;
         }
        break;

        case 27:
#line 197 "while.y"
        {
         std::cout << "branch -> T_IF expression T_THEN statements T_ENDIF" << std::endl;
         }
        break;

        case 28:
#line 202 "while.y"
        {
         std::cout << "branch -> T_IF expression T_THEN statements T_ELSE statements T_ENDIF" << std::endl;
         }
        break;

        case 29:
#line 209 "while.y"
        {
         std::cout << "loop -> T_WHILE expression T_DO statements T_DONE" << std::endl;
         }
        break;

        case 30:
#line 216 "while.y"
        {
         std::cout << "expression -> T_NUM" << std::endl;
         }
        break;

        case 31:
#line 221 "while.y"
        {
         std::cout << "expression -> T_TRUE" << std::endl;
         }
        break;

        case 32:
#line 226 "while.y"
        {
         std::cout << "expression -> T_FALSE" << std::endl;
         }
        break;

        case 33:
#line 231 "while.y"
        {
         std::cout << "expression -> T_ID" << std::endl;
         }
        break;

        case 34:
#line 236 "while.y"
        {
         std::cout << "expression -> expression T_ADD expression" << std::endl;
         }
        break;

        case 35:
#line 241 "while.y"
        {
         std::cout << "expression -> expression T_SUB expression" << std::endl;
         }
        break;

        case 36:
#line 246 "while.y"
        {
         std::cout << "expression -> expression T_MUL expression" << std::endl;
         }
        break;

        case 37:
#line 251 "while.y"
        {
         std::cout << "expression -> expression T_DIV expression" << std::endl;
         }
        break;

        case 38:
#line 256 "while.y"
        {
         std::cout << "expression -> expression T_MOD expression" << std::endl;
         }
        break;

        case 39:
#line 261 "while.y"
        {
         std::cout << "expression -> expression T_LESS expression" << std::endl;
         }
        break;

        case 40:
#line 266 "while.y"
        {
         std::cout << "expression -> expression T_GR expression" << std::endl;
         }
        break;

        case 41:
#line 271 "while.y"
        {
         std::cout << "expression -> expression T_EQ expression" << std::endl;
         }
        break;

        case 42:
#line 276 "while.y"
        {
         std::cout << "expression -> expression T_AND expression" << std::endl;
         }
        break;

        case 43:
#line 281 "while.y"
        {
         std::cout << "expression -> expression T_OR expression" << std::endl;
         }
        break;

        case 44:
#line 286 "while.y"
        {
         std::cout << "expression -> T_NOT expression" << std::endl;
         }
        break;

        case 45:
#line 291 "while.y"
        {
         std::cout << "expression -> T_OPEN expression T_CLOSE" << std::endl;
         }
        break;

        case 46:
#line 296 "while.y"
        {
         std::cout << "expression -> T_HOUR T_OPEN T_ID T_CLOSE" << std::endl;
         }
        break;

        case 47:
#line 301 "while.y"
        {
         std::cout << "expression -> T_MINUTE T_OPEN T_ID T_CLOSE" << std::endl;
         }
        break;

        case 48:
#line 306 "while.y"
        {
         std::cout << "expression -> T_ID T_OPEN_B expression T_CLOSE_B" << std::endl;
         }
        break;

    }
}
catch (std::exception const &exc)
{
    exceptionHandler__(exc);
}

inline void ParserBase::reduce__(PI__ const &pi)
{
    d_token__ = pi.d_nonTerm;
    pop__(pi.d_size);

}

// If d_token__ is _UNDETERMINED_ then if d_nextToken__ is _UNDETERMINED_ another
// token is obtained from lex(). Then d_nextToken__ is assigned to d_token__.
void Parser::nextToken()
{
    if (d_token__ != _UNDETERMINED_)        // no need for a token: got one
        return;                             // already

    if (d_nextToken__ != _UNDETERMINED_)
    {
        popToken__();                       // consume pending token
    }
    else
    {
        ++d_acceptedTokens__;               // accept another token (see
                                            // errorRecover())
        d_token__ = lex();
        if (d_token__ <= 0)
            d_token__ = _EOF_;
    }
    print();
}

// if the final transition is negative, then we should reduce by the rule
// given by its positive value. Note that the `recovery' parameter is only
// used with the --debug option
int Parser::lookup(bool recovery)
{
// $insert threading
    SR__ *sr = s_state[d_state__];          // get the appropriate state-table
    int lastIdx = sr->d_lastIdx;            // sentinel-index in the SR__ array
    
    SR__ *lastElementPtr = sr + lastIdx;
    lastElementPtr->d_token = d_token__;    // set search-token
    
    SR__ *elementPtr = sr + 1;              // start the search at s_xx[1]
    while (elementPtr->d_token != d_token__)
        ++elementPtr;
    

    if (elementPtr == lastElementPtr)   // reached the last element
    {
        if (elementPtr->d_action < 0)   // default reduction
        {
            return elementPtr->d_action;                
        }

        // No default reduction, so token not found, so error.
        throw UNEXPECTED_TOKEN__;
    }

    // not at the last element: inspect the nature of the action
    // (< 0: reduce, 0: ACCEPT, > 0: shift)

    int action = elementPtr->d_action;


    return action;
}

    // When an error has occurred, pop elements off the stack until the top
    // state has an error-item. If none is found, the default recovery
    // mode (which is to abort) is activated. 
    //
    // If EOF is encountered without being appropriate for the current state,
    // then the error recovery will fall back to the default recovery mode.
    // (i.e., parsing terminates)
void Parser::errorRecovery()
try
{
    if (d_acceptedTokens__ >= d_requiredTokens__)// only generate an error-
    {                                           // message if enough tokens 
        ++d_nErrors__;                          // were accepted. Otherwise
        error("Syntax error");                  // simply skip input

    }


    // get the error state
    while (not (s_state[top__()][0].d_type & ERR_ITEM))
    {
        pop__();
    }

    // In the error state, lookup a token allowing us to proceed.
    // Continuation may be possible following multiple reductions,
    // but eventuall a shift will be used, requiring the retrieval of
    // a terminal token. If a retrieved token doesn't match, the catch below 
    // will ensure the next token is requested in the while(true) block
    // implemented below:

    int lastToken = d_token__;                  // give the unexpected token a
                                                // chance to be processed
                                                // again.

    pushToken__(_error_);                       // specify _error_ as next token
    push__(lookup(true));                       // push the error state

    d_token__ = lastToken;                      // reactivate the unexpected
                                                // token (we're now in an
                                                // ERROR state).

    bool gotToken = true;                       // the next token is a terminal

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
            {
                gotToken = d_token__ == _UNDETERMINED_;
                nextToken();                    // obtain next token
            }
            
            int action = lookup(true);

            if (action > 0)                 // push a new state
            {
                push__(action);
                popToken__();

                if (gotToken)
                {

                    d_acceptedTokens__ = 0;
                    return;
                }
            }
            else if (action < 0)
            {
                // no actions executed on recovery but save an already 
                // available token:
                if (d_token__ != _UNDETERMINED_)
                    pushToken__(d_token__);
 
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else
                ABORT();                    // abort when accepting during
                                            // error recovery
        }
        catch (...)
        {
            if (d_token__ == _EOF_)
                ABORT();                    // saw inappropriate _EOF_
                      
            popToken__();                   // failing token now skipped
        }
    }
}
catch (ErrorRecovery__)       // This is: DEFAULT_RECOVERY_MODE
{
    ABORT();
}

    // The parsing algorithm:
    // Initially, state 0 is pushed on the stack, and d_token__ as well as
    // d_nextToken__ are initialized to _UNDETERMINED_. 
    //
    // Then, in an eternal loop:
    //
    //  1. If a state does not have REQ_TOKEN no token is assigned to
    //     d_token__. If the state has REQ_TOKEN, nextToken() is called to
    //      determine d_nextToken__ and d_token__ is set to
    //     d_nextToken__. nextToken() will not call lex() unless d_nextToken__ is 
    //     _UNDETERMINED_. 
    //
    //  2. lookup() is called: 
    //     d_token__ is stored in the final element's d_token field of the
    //     state's SR_ array. 
    //
    //  3. The current token is looked up in the state's SR_ array
    //
    //  4. Depending on the result of the lookup() function the next state is
    //     shifted on the parser's stack, a reduction by some rule is applied,
    //     or the parsing function returns ACCEPT(). When a reduction is
    //     called for, any action that may have been defined for that
    //     reduction is executed.
    //
    //  5. An error occurs if d_token__ is not found, and the state has no
    //     default reduction. Error handling was described at the top of this
    //     file.

int Parser::parse()
try 
{
    push__(0);                              // initial state
    clearin();                              // clear the tokens.

    while (true)
    {
        try
        {
            if (s_state[d_state__]->d_type & REQ_TOKEN)
                nextToken();                // obtain next token


            int action = lookup(false);     // lookup d_token__ in d_state__

            if (action > 0)                 // SHIFT: push a new state
            {
                push__(action);
                popToken__();               // token processed
            }
            else if (action < 0)            // REDUCE: execute and pop.
            {
                executeAction(-action);
                                            // next token is the rule's LHS
                reduce__(s_productionInfo[-action]); 
            }
            else 
                ACCEPT();
        }
        catch (ErrorRecovery__)
        {
            errorRecovery();
        }
    }
}
catch (Return__ retValue)
{
    return retValue;
}



